package engine

// Register Providers

import (
	_ "github.com/HDuoDuo/metatube/provider/10musume"
	_ "github.com/HDuoDuo/metatube/provider/1pondo"
	_ "github.com/HDuoDuo/metatube/provider/airav"
	_ "github.com/HDuoDuo/metatube/provider/arzon"
	_ "github.com/HDuoDuo/metatube/provider/av-league"
	_ "github.com/HDuoDuo/metatube/provider/avbase"
	_ "github.com/HDuoDuo/metatube/provider/aventertainments"
	_ "github.com/HDuoDuo/metatube/provider/c0930"
	_ "github.com/HDuoDuo/metatube/provider/caribbeancom"
	_ "github.com/HDuoDuo/metatube/provider/caribbeancompr"
	_ "github.com/HDuoDuo/metatube/provider/dahlia"
	_ "github.com/HDuoDuo/metatube/provider/duga"
	_ "github.com/HDuoDuo/metatube/provider/faleno"
	_ "github.com/HDuoDuo/metatube/provider/fanza"
	_ "github.com/HDuoDuo/metatube/provider/fc2"
	_ "github.com/HDuoDuo/metatube/provider/fc2hub"
	_ "github.com/HDuoDuo/metatube/provider/gcolle"
	_ "github.com/HDuoDuo/metatube/provider/getchu"
	_ "github.com/HDuoDuo/metatube/provider/gfriends"
	_ "github.com/HDuoDuo/metatube/provider/h0930"
	_ "github.com/HDuoDuo/metatube/provider/h4610"
	_ "github.com/HDuoDuo/metatube/provider/heydouga"
	_ "github.com/HDuoDuo/metatube/provider/heyzo"
	_ "github.com/HDuoDuo/metatube/provider/jav321"
	_ "github.com/HDuoDuo/metatube/provider/javbus"
	_ "github.com/HDuoDuo/metatube/provider/kin8tengoku"
	_ "github.com/HDuoDuo/metatube/provider/mgstage"
	_ "github.com/HDuoDuo/metatube/provider/muramura"
	_ "github.com/HDuoDuo/metatube/provider/mywife"
	_ "github.com/HDuoDuo/metatube/provider/pacopacomama"
	_ "github.com/HDuoDuo/metatube/provider/pcolle"
	_ "github.com/HDuoDuo/metatube/provider/sod"
	_ "github.com/HDuoDuo/metatube/provider/tokyo-hot"
	_ "github.com/HDuoDuo/metatube/provider/xxx-av"
)
