name: Docker Image Build

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      
jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build Metatube Docker Image
    steps:
      -
        name: Checkout
        uses: actions/checkout@main

      -
        name: Release version
        id: release_version
        run: |
          app_version="1.2.8"
          echo "app_version=$app_version" >> $GITHUB_ENV

      -
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/metatube:latest
            ${{ secrets.DOCKER_USERNAME }}/metatube:${{ env.app_version }}